// 직군 (대분류)
export const fieldOptions: string[] = [
  '마케팅',
  '서비스 기획',
  '디자인',
  '개발',
  '대학원',
  '인사',
  '영업',
  '금융',
  '데이터',
  '의료',
  '법률',
];

// 직무 (세부 카테고리)
export const subFieldOptions: { [key: string]: string[] } = {
  전체: [],
  마케팅: [
    '브랜드 마케팅',
    '퍼포먼스 마케팅',
    '디지털/소셜 마케팅',
    '그로스 마케팅',
    'PR',
    'AE',
    '콘텐츠 마케팅',
    '크리에이티브 디렉팅',
    '카피라이터',
    '미디어 플래너',
    '방송PD/영상PD',
    '기타',
  ],
  '서비스 기획': [
    '서비스기획',
    'PM/PO',
    '전략 기획',
    '운영/기획',
    '사업 개발',
    'CX 매니저',
    '창업',
    '기타',
  ],
  디자인: [
    'UX/UI디자인',
    '그래픽 디자인',
    '상품 디자인',
    '브랜드 디자인',
    '웹 디자인',
    '아트 디렉터',
    '기타',
  ],
  개발: [
    '프론트엔드',
    '백엔드',
    '풀스택 개발자',
    'iOS/Android 개발자',
    'DevOps 엔지니어',
    '클라우드 엔지니어',
    '시스템/네트워크 엔지니어',
    '보안 엔지니어',
    '기타',
  ],
  대학원: ['국내 대학원', '해외 대학원', '기타'],
  인사: [
    '인사기획',
    '채용담당',
    '인재육성/교육담당',
    '조직문화담당',
    '노무담당',
    '총무/경영지원',
    '인사운영',
    '리크루터',
    '기타',
  ],
  영업: [
    '기업영업(B2B)',
    '개인영업(B2C)',
    '해외영업',
    '기술영업',
    '솔루션 컨설턴트',
    '주요고객관리(KAM)',
    '영업관리/지원',
    'CSM/CX',
    '기타',
  ],
  금융: [
    '컨설턴트',
    'VC/투자',
    'IB/PE/대체투자',
    '에널리스트',
    '회계/재무',
    '기타',
  ],
  데이터: [
    '데이터 사이언티스트',
    '데이터 엔지니어',
    '데이터 애널리스트',
    'BI 엔지니어',
    '머신러닝 엔지니어',
    '데이터 아키텍트',
    '리서치 애널리스트',
    '기타',
  ],
  의료: [
    '임상의사',
    '임상연구원',
    '의료기기 연구개발',
    '제약회사 연구원',
    '바이오 연구원',
    '기타',
  ],
  법률: [
    '변호사',
    '법무담당',
    '특허담당',
    '준법감시인(컴플라이언스)',
    '법무법인 사무직',
    '법률자문',
    '특허엔지니어',
    '기타',
  ],
};

export const jobCategoryMapping: { [key: string]: string } = {
  마케팅: 'MARKETING',
  '서비스 기획': 'SERVICE_PLANNING',
  디자인: 'DESIGN',
  개발: 'DEVELOPMENT',
  대학원: 'GRADUATE_SCHOOL',
  인사: 'HR_SUPPORT',
  영업: 'SALES_CUSTOMER',
  금융: 'FINANCE_CONSULTING_VC',
  데이터: 'DATA',
  의료: 'MEDICAL',
  법률: 'LEGAL',
};

export const detailedJobMapping: { [key: string]: string } = {
  '브랜드 마케팅': 'BRAND_MARKETING',
  '퍼포먼스 마케팅': 'PERFORMANCE_MARKETING',
  '디지털/소셜 마케팅': 'DIGITAL_SOCIAL_MARKETING',
  '그로스 마케팅': 'GROWTH_MARKETING',
  PR: 'PR',
  AE: 'AE',
  '콘텐츠 마케팅': 'CONTENT_MARKETING',
  '크리에이티브 디렉팅': 'CREATIVE_DIRECTING',
  카피라이터: 'COPYWRITER',
  '미디어 플래너': 'MEDIA_PLANNER',
  '방송PD/영상PD': 'BROADCAST_PD',
  서비스기획: 'SERVICE_PLANNING',
  'PM/PO': 'PM_PO',
  '전략 기획': 'STRATEGY_PLANNING',
  '운영/기획': 'OPERATION_PLANNING',
  '사업 개발': 'BUSINESS_DEVELOPMENT',
  'CX 매니저': 'CX_MANAGER',
  창업: 'STARTUP',
  'UX/UI디자인': 'UX_UI_DESIGN',
  '그래픽 디자인': 'GRAPHIC_DESIGN',
  '상품 디자인': 'PRODUCT_DESIGN',
  '브랜드 디자인': 'BRAND_DESIGN',
  '웹 디자인': 'WEB_DESIGN',
  '아트 디렉터': 'ART_DIRECTOR',
  프론트엔드: 'FRONTEND',
  백엔드: 'BACKEND',
  '풀스택 개발자': 'FULLSTACK',
  'iOS/Android 개발자': 'IOS_ANDROID',
  'DevOps 엔지니어': 'DEVOPS',
  '클라우드 엔지니어': 'CLOUD',
  '시스템/네트워크 엔지니어': 'SYSTEM_NETWORK',
  '보안 엔지니어': 'SECURITY',
  '국내 대학원': 'DOMESTIC_GRADUATE_SCHOOL',
  '해외 대학원': 'OVERSEAS_GRADUATE_SCHOOL',
  인사기획: 'HR_PLANNING',
  채용담당: 'RECRUITMENT',
  '인재육성/교육담당': 'TALENT_DEVELOPMENT',
  조직문화담당: 'ORGANIZATION_CULTURE',
  노무담당: 'LABOR',
  '총무/경영지원': 'GENERAL_AFFAIRS',
  리크루터: 'RECRUITER',
  '기업영업(B2B)': 'B2B_SALES',
  '개인영업(B2C)': 'B2C_SALES',
  해외영업: 'OVERSEAS_SALES',
  기술영업: 'TECHNICAL_SALES',
  컨설턴트: 'CONSULTANT',
  'VC/투자': 'VC_INVESTMENT',
  'IB/PE/대체투자': 'IB_PE_ALTERNATIVE_INVESTMENT',
  에널리스트: 'ANALYST',
  '데이터 사이언티스트': 'DATA_SCIENTIST',
  '데이터 엔지니어': 'DATA_ENGINEER',
  '데이터 애널리스트': 'DATA_ANALYST',
  'BI 엔지니어': 'BI_ENGINEER',
  '머신러닝 엔지니어': 'MACHINE_LEARNING_ENGINEER',
  임상의사: 'CLINICAL_DOCTOR',
  임상연구원: 'CLINICAL_RESEARCHER',
  '의료기기 연구개발': 'MEDICAL_DEVICE_RND',
  '제약회사 연구원': 'PHARMACEUTICAL_RESEARCHER',
  '바이오 연구원': 'BIO_RESEARCHER',
  변호사: 'LAWYER',
  법무담당: 'LEGAL_COUNSEL',
  특허담당: 'PATENT',
  '준법감시인(컴플라이언스)': 'COMPLIANCE',
  '법무법인 사무직': 'LAW_FIRM_STAFF',
  법률자문: 'LEGAL_ADVISOR',
};
